import type { Neighbourhood } from '../types';

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function todayISO(): string {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
}

function fmtMoney(n: number): string {
  return `$${n.toLocaleString()}`;
}

function fmtMoneyShort(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(1)}K`;
  return fmtMoney(n);
}

export function buildBriefingMarkdown(nb: Neighbourhood): string {
  const date = todayISO();
  const secondaryImpact = Math.round(
    nb.eligible_households * nb.secondaryBenefit,
  );

  return `# Neighbourhood Priority Briefing

**Neighbourhood:** ${nb.name}
**Rank:** #${nb.rank} of 158
**Tier:** ${nb.tier}
**Energy Burden Index (EBI):** ${nb.ebi.toFixed(3)}
**Briefing date:** ${date}

---

## Score Breakdown

| Component | Weight | Score (0–1) |
|---|---|---|
| Income          | 35% | ${nb.income.toFixed(3)} |
| Renter          | 25% | ${nb.renter.toFixed(3)} |
| Consumption     | 25% | ${nb.consumption.toFixed(3)} |
| Building Age    | 15% | ${nb.age.toFixed(3)} |

**Formula:** EBI = 0.35 × Income + 0.25 × Renter + 0.25 × Consumption + 0.15 × Age

---

## Raw Indicators

| Indicator | Value |
|---|---|
| Estimated annual electricity use | ${nb.est_kwh.toLocaleString()} kWh/household |
| Renter share of households       | ${(nb.renter_pct * 100).toFixed(1)}% |
| Dominant dwelling type           | ${nb.dwelling} |

---

## Recommended Programs

### Primary — ${nb.primaryName}
- **Eligibility:** ${nb.primaryEligibility}
- **Annual benefit per household:** ${fmtMoney(nb.primaryBenefit)}
- **Eligible households (this neighbourhood):** ${nb.eligible_households.toLocaleString()}
- **Estimated total annual benefit:** ${fmtMoney(nb.total_annual_benefit)}

### Secondary — ${nb.secondaryName}
- **Eligibility:** ${nb.secondaryEligibility}
- **Annual benefit per household:** ${fmtMoney(nb.secondaryBenefit)}
- **Estimated total annual benefit (same uptake):** ${fmtMoney(secondaryImpact)}

---

## Impact Summary

If **${nb.uptake_assumption}** of eligible households enroll in the primary program, an estimated **${fmtMoney(nb.total_annual_benefit)}** in annual benefit will be delivered to **${nb.eligible_households.toLocaleString()} households** in ${nb.name}.

---

## Data Sources

- **NRCan Survey of Household Energy Use (SHEU 2021)** — natural gas and electricity consumption by dwelling type. https://oee.nrcan.gc.ca/publications/statistics/sheu/2021/
- **Statistics Canada Census 2021 — National Household Survey** — household income quintiles and tenure aggregated to Toronto's 158 City Planning Neighbourhoods. https://www12.statcan.gc.ca/census-recensement/2021/
- **Statistics Canada Census 2021 — Dwelling Characteristics** — period of construction used to compute the age factor.
- **Ontario Energy Board (OEB) — Regulated Price Plan, Q1 2024** — Time-of-Use rates used in kWh-to-annual-cost conversion. https://www.oeb.ca/rates-and-your-bill/electricity-rates
- **City of Toronto Open Data — Neighbourhood Profiles 2021** — 158 neighbourhood boundary definitions. https://open.toronto.ca/dataset/neighbourhood-profiles/

---

_Generated by EquiGrid · Energy Burden Index for Toronto · ${date}_
`;
}

export function exportBriefing(nb: Neighbourhood): void {
  const md = buildBriefingMarkdown(nb);
  const filename = `briefing-${slugify(nb.name)}-${todayISO()}.md`;

  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  // Release the object URL on the next tick so the download has a chance to start.
  setTimeout(() => URL.revokeObjectURL(url), 0);

  // TODO: PDF export — wire up jsPDF or html2pdf here when product wants a PDF
  // version of the briefing. Pass `md` through a markdown-to-PDF pipeline or
  // render a hidden HTML element and snapshot it.
}

export function previewBriefing(nb: Neighbourhood): string {
  return buildBriefingMarkdown(nb);
}
