import type { Neighbourhood } from '../types';
import { PROGRAM_COLORS, TIER_COLORS } from '../data/constants';

import html2pdf from 'html2pdf.js';

const TOTAL_NEIGHBOURHOODS = 158;

function todayISO(): string {
  return new Date().toISOString().split('T')[0];
}

function fmtMoney(n: number): string {
  return `$${n.toLocaleString()}`;
}

export function buildBriefingMarkdown(nb: Neighbourhood): string {
  const date = todayISO();
  const secondaryImpact = Math.round(
    nb.eligible_households * nb.secondaryBenefit,
  );

  return `# Neighbourhood Priority Briefing

**Neighbourhood:** ${nb.name}
**Rank:** #${nb.rank} of 158
**Tier:** ${nb.tier}
**Energy Burden Index (EBI):** ${nb.ebi.toFixed(3)}
**Briefing date:** ${date}

---

## Score Breakdown

| Component | Weight | Score (0–1) |
|---|---|---|
| Income          | 35% | ${nb.income.toFixed(3)} |
| Renter          | 25% | ${nb.renter.toFixed(3)} |
| Consumption     | 25% | ${nb.consumption.toFixed(3)} |
| Building Age    | 15% | ${nb.age.toFixed(3)} |

**Formula:** EBI = 0.35 × Income + 0.25 × Renter + 0.25 × Consumption + 0.15 × Age

---

## Raw Indicators

| Indicator | Value |
|---|---|
| Estimated annual electricity use | ${nb.est_kwh.toLocaleString()} kWh/household |
| Renter share of households       | ${(nb.renter_pct * 100).toFixed(1)}% |
| Dominant dwelling type           | ${nb.dwelling} |

---

## Recommended Programs

### Primary — ${nb.primaryName}
- **Eligibility:** ${nb.primaryEligibility}
- **Annual benefit per household:** ${fmtMoney(nb.primaryBenefit)}
- **Eligible households (this neighbourhood):** ${nb.eligible_households.toLocaleString()}
- **Estimated total annual benefit:** ${fmtMoney(nb.total_annual_benefit)}

### Secondary — ${nb.secondaryName}
- **Eligibility:** ${nb.secondaryEligibility}
- **Annual benefit per household:** ${fmtMoney(nb.secondaryBenefit)}
- **Estimated total annual benefit (same uptake):** ${fmtMoney(secondaryImpact)}

---

## Impact Summary

If **${nb.uptake_assumption}** of eligible households enroll in the primary program, an estimated **${fmtMoney(nb.total_annual_benefit)}** in annual benefit will be delivered to **${nb.eligible_households.toLocaleString()} households** in ${nb.name}.

---

## Data Sources

- **NRCan Survey of Household Energy Use (SHEU 2021)** — natural gas and electricity consumption by dwelling type. https://oee.nrcan.gc.ca/publications/statistics/sheu/2021/
- **Statistics Canada Census 2021 — National Household Survey** — household income quintiles and tenure aggregated to Toronto's 158 City Planning Neighbourhoods. https://www12.statcan.gc.ca/census-recensement/2021/
- **Statistics Canada Census 2021 — Dwelling Characteristics** — period of construction used to compute the age factor.
- **Ontario Energy Board (OEB) — Regulated Price Plan, Q1 2024** — Time-of-Use rates used in kWh-to-annual-cost conversion. https://www.oeb.ca/rates-and-your-bill/electricity-rates
- **City of Toronto Open Data — Neighbourhood Profiles 2021** — 158 neighbourhood boundary definitions. https://open.toronto.ca/dataset/neighbourhood-profiles/

---

_Generated by EquiGrid · Energy Burden Index for Toronto · ${date}_
`;
}

function buildTemplateVars(nb: Neighbourhood): Record<string, string> {
  const tc = TIER_COLORS[nb.tier];
  const tierBadgeStyle = `background:${tc.light};border:1px solid ${tc.bg}`;
  const tierDotStyle = `background:${tc.bg}`;
  const tierTextStyle = `color:${tc.text}`;
  const secondaryTotalImpact = Math.round(
    nb.eligible_households * nb.secondaryBenefit,
  );

  return {
    briefingDate: todayISO(),
    neighbourhoodName: nb.name,
    rank: String(nb.rank),
    totalNeighbourhoods: String(TOTAL_NEIGHBOURHOODS),
    ebiScore: nb.ebi.toFixed(3),
    tierLabel: nb.tier,
    tierBadgeStyle,
    tierDotStyle,
    tierTextStyle,
    incomeScore: nb.income.toFixed(3),
    renterScore: nb.renter.toFixed(3),
    consumptionScore: nb.consumption.toFixed(3),
    ageScore: nb.age.toFixed(3),
    incomeBarWidth: (nb.income * 100).toFixed(1),
    renterBarWidth: (nb.renter * 100).toFixed(1),
    consumptionBarWidth: (nb.consumption * 100).toFixed(1),
    ageBarWidth: (nb.age * 100).toFixed(1),
    renterPct: (nb.renter_pct * 100).toFixed(1),
    estKwh: nb.est_kwh.toLocaleString(),
    dominantDwelling: nb.dwelling,
    primaryProgramStyle: `background:${PROGRAM_COLORS[nb.primaryKey].bg}`,
    primaryProgramName: nb.primaryName,
    primaryEligibility: nb.primaryEligibility,
    primaryBenefit: nb.primaryBenefit.toLocaleString(),
    primaryEligibleHH: nb.eligible_households.toLocaleString(),
    primaryTotalImpact: nb.total_annual_benefit.toLocaleString(),
    secondaryProgramStyle: `background:${PROGRAM_COLORS[nb.secondaryKey].bg}`,
    secondaryProgramName: nb.secondaryName,
    secondaryEligibility: nb.secondaryEligibility,
    secondaryBenefit: nb.secondaryBenefit.toLocaleString(),
    secondaryEligibleHH: nb.eligible_households.toLocaleString(),
    secondaryTotalImpact: secondaryTotalImpact.toLocaleString(),
    projectedAmount: nb.total_annual_benefit.toLocaleString(),
    projectedHH: nb.eligible_households.toLocaleString(),
  };
}

function applyTemplate(html: string, vars: Record<string, string>): string {
  let out = html;
  for (const [key, value] of Object.entries(vars)) {
    out = out.split(`{{${key}}}`).join(value);
  }
  return out;
}

function waitForIframeReady(iframe: HTMLIFrameElement): Promise<Document> {
  return new Promise((resolve, reject) => {
    const onLoad = () => {
      const doc = iframe.contentDocument;
      if (!doc) {
        reject(new Error('Export iframe has no document'));
        return;
      }
      resolve(doc);
    };
    iframe.addEventListener('load', onLoad, { once: true });
    setTimeout(() => {
      if (iframe.contentDocument?.body?.childElementCount) {
        onLoad();
      }
    }, 500);
  });
}

async function htmlBriefingToPdf(nb: Neighbourhood): Promise<void> {
  const response = await fetch('/briefing_template.html');
  if (!response.ok) {
    throw new Error(`Failed to load briefing template (${response.status})`);
  }

  const templateHtml = await response.text();
  const populatedHtml = applyTemplate(templateHtml, buildTemplateVars(nb));

  if (/\{\{[a-zA-Z]+\}\}/.test(populatedHtml)) {
    console.warn(
      '[exportBriefing] Unreplaced template placeholders:',
      populatedHtml.match(/\{\{[a-zA-Z]+\}\}/g),
    );
  }

  const iframe = document.createElement('iframe');
  iframe.setAttribute('aria-hidden', 'true');
  iframe.setAttribute('title', 'Briefing export');
  iframe.style.position = 'fixed';
  iframe.style.top = '0';
  iframe.style.left = '-794px';
  iframe.style.width = '794px';
  iframe.style.height = '1200px';
  iframe.style.border = 'none';
  iframe.style.pointerEvents = 'none';
  document.body.appendChild(iframe);

  const filename = `equigrid_briefing_${nb.name.replace(/\s+/g, '_')}.pdf`;

  try {
    const doc = iframe.contentDocument;
    if (!doc) throw new Error('Could not create export iframe document');
    doc.open();
    doc.write(populatedHtml);
    doc.close();

    const readyDoc = await waitForIframeReady(iframe);
    await readyDoc.fonts?.ready;
    await new Promise((resolve) => setTimeout(resolve, 200));

    const target =
      (readyDoc.body.firstElementChild as HTMLElement | null) ??
      readyDoc.body;

    await html2pdf()
      .set({
        margin: 0,
        filename,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          backgroundColor: '#ffffff',
          windowWidth: 794,
          scrollX: 0,
          scrollY: 0,
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      })
      .from(target)
      .save();
  } finally {
    document.body.removeChild(iframe);
  }
}

export function exportBriefing(nb: Neighbourhood): void {
  htmlBriefingToPdf(nb).catch((err: unknown) => {
    console.error('[exportBriefing] PDF generation failed:', err);
  });
}

export function previewBriefing(nb: Neighbourhood): string {
  return buildBriefingMarkdown(nb);
}
